const prefix = "offerCourse";

//POST
export const SAVE_OFFER_COURSE = `${prefix}/SAVE_OFFER_COURSE`;
export const SAVE_OFFER_COURSE_LOADING = `${prefix}/SAVE_OFFER_COURSE_LOADING`;
export const SAVE_OFFER_COURSE_SUCCESS = `${prefix}/SAVE_OFFER_COURSE_SUCCESS`;
export const SAVE_OFFER_COURSE_FAILED = `${prefix}/SAVE_OFFER_COURSE_FAILED`;

//GET
export const FETCH_OFFER_COURSE_LIST = `${prefix}/GET_OFFER_COURSE_LIST`;
export const SET_OFFER_COURSE_LIST_LOADING = `${prefix}/SET_OFFER_COURSE_LIST_LOADING`;
export const GET_OFFER_COURSE_LIST_SUCCESS = `${prefix}/GET_OFFER_COURSE_LIST_SUCCESS`;
export const GET_OFFER_COURSE_LIST_FAILED = `${prefix}/GET_OFFER_COURSE_LIST_FAILED`;