const prefix = "pendingTutorListShow";

export const FETCH_PENDING_TUTOR_SHOW_LIST = `${prefix}/GET_PENDING_TUTOR_SHOW_LIST`;
export const SET_PENDING_TUTOR_SHOW_LIST_LOADING = `${prefix}/SET_PENDING_TUTOR_SHOW_LIST_LOADING`;
export const GET_PENDING_TUTOR_SHOW_LIST_SUCCESS = `${prefix}/GET_PENDING_TUTOR_SHOW_LIST_SUCCESS`;
export const GET_PENDING_TUTOR_SHOW_LIST_FAILED = `${prefix}/GET_PENDING_TUTOR_SHOW_LIST_FAILED`;
