-- MySQL Script generated by MySQL Workbench
-- Fri Dec 24 18:04:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema helpmelearn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema helpmelearn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `helpmelearn` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `helpmelearn` ;

-- -----------------------------------------------------
-- Table `helpmelearn`.`tutorprofile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpmelearn`.`tutorprofile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `subject` VARCHAR(100) NOT NULL,
  `age` INT NOT NULL,
  `level` VARCHAR(45) NULL DEFAULT NULL,
  `rate` FLOAT NULL DEFAULT NULL,
  `rating` FLOAT NULL DEFAULT NULL,
  `numOfStudents` INT NULL DEFAULT NULL COMMENT '	',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helpmelearn`.`hm_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpmelearn`.`hm_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `usertype` INT NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `status` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helpmelearn`.`hm_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpmelearn`.`hm_post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subjectTitle` VARCHAR(50) NOT NULL,
  `description` VARCHAR(50) NULL,
  `tutorId` VARCHAR(100) NOT NULL,
  `status` INT NOT NULL,
  `language` VARCHAR(45) NULL DEFAULT NULL,
  `subjectCode` FLOAT NOT NULL,
  `ratePerHour` FLOAT NULL DEFAULT NULL,
  `createdDateTime` DATE NOT NULL,
  `modifiedDateTime` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helpmelearn`.`hm_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpmelearn`.`hm_review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(150) NOT NULL,
  `rating` FLOAT NULL,
  `createdDateTime` DATE NOT NULL,
  `modifiedDateTime` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helpmelearn`.`hm_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpmelearn`.`hm_image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imagePath` VARCHAR(50) NOT NULL,
  `date` VARCHAR(50) NULL,
  `userId` VARCHAR(100) NOT NULL,
  `createdDateTime` DATE NOT NULL,
  `modifiedDateTime` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
